---
apiVersion: v1
kind: Secret
metadata:
  name: ssh-argocd
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: git@github.com:xcheng85/gitops-test-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    -----END OPENSSH PRIVATE KEY-----
  insecure: "false"
  enableLfs: "true"